# .github/workflows/release.yml

name: Release Pot-App Plugin

on:
  # 允许手动触发
  workflow_dispatch:
    inputs:
      # 定义一个输入参数，让你可以手动指定版本号
      version:
        description: 'The release version tag (e.g., v1.0.0)'
        required: true # 设为必填项

  # (保留)推送 tag 触发器，这样本地操作也依然有效
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Plugin ID
        id: get_id
        run: echo "id=$(jq -r .id info.json)" >> $GITHUB_OUTPUT

      - name: Package Plugin
        run: zip -r plugin.zip info.json main.js *.svg

      - name: Rename Package
        id: rename
        run: |
          filename="${{ steps.get_id.outputs.id }}.potext"
          mv plugin.zip $filename
          echo "filename=$filename" >> $GITHUB_OUTPUT

      # 关键改动：决定 Release 的 tag 和名称
      - name: Set Release Version
        id: set_version
        run: |
          # 如果是手动触发，使用输入的 version；如果是 tag 触发，使用 tag 名称
          VERSION=${{ github.event.inputs.version || github.ref_name }}
          echo "RELEASE_VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ steps.rename.outputs.filename }}
          # 使用上一步确定的版本号作为 tag 和 Release 名称
          tag_name: ${{ steps.set_version.outputs.RELEASE_VERSION }}
          name: Release ${{ steps.set_version.outputs.RELEASE_VERSION }}
          generate_release_notes: true
